package genieprojet.gui;

import genieprojet.controleurs.CatalogueControleur;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.text.InternationalFormatter;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Julien Cossette
 */
public class AddItemWindow extends javax.swing.JFrame {
    private CatalogueControleur myControler;

    /**
     * Creates new form ajouterItemWindow
     *
     * @param myControler Controler to assign to this window
     */
    public AddItemWindow(CatalogueControleur myControler) {
        this.myControler = myControler;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noteLabel = new javax.swing.JLabel();
        noteField = new javax.swing.JScrollPane();
        noteField1 = new javax.swing.JTextArea();
        ajouterButton = new javax.swing.JButton();
        nomLabel = new javax.swing.JLabel();
        incrButton = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        decrButton = new javax.swing.JButton();
        qtyLabel = new javax.swing.JLabel();
        NumberFormat myFormat = NumberFormat.getIntegerInstance();
        myFormat.setMinimumIntegerDigits(0);
        NumberFormatter numberFormatter = new NumberFormatter(myFormat);
        numberFormatter.setValueClass(Long.class);
        numberFormatter.setAllowsInvalid(false);
        qtyField = new javax.swing.JFormattedTextField(numberFormatter);
        prixLabel = new javax.swing.JLabel();
        NumberFormat format = DecimalFormat.getInstance();
        format.setMinimumFractionDigits(2);
        format.setMaximumFractionDigits(2);
        format.setRoundingMode(RoundingMode.HALF_UP);
        InternationalFormatter formatter = new InternationalFormatter(format);
        formatter.setAllowsInvalid(false);
        prixField = new javax.swing.JFormattedTextField(formatter);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        noteLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        noteLabel.setText("Note:");

        noteField1.setColumns(20);
        noteField1.setRows(5);
        noteField.setViewportView(noteField1);

        ajouterButton.setText("Ajouter");
        ajouterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterButtonActionPerformed(evt);
            }
        });

        nomLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomLabel.setText("Nom:");

        incrButton.setText("+");
        incrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incrButtonActionPerformed(evt);
            }
        });

        decrButton.setText("-");
        decrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrButtonActionPerformed(evt);
            }
        });

        qtyLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qtyLabel.setText("Quantité:");

        qtyField.setText("0");

        prixLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prixLabel.setText("Prix:");

        prixField.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(qtyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(incrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ajouterButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noteLabel)
                            .addComponent(prixLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noteField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prixField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyField, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(qtyLabel)
                    .addComponent(incrButton)
                    .addComponent(decrButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prixLabel)
                    .addComponent(prixField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noteLabel)
                    .addComponent(noteField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ajouterButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void ajouterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterButtonActionPerformed
       String nom = nameField.getText();
       int qty = Integer.parseInt(qtyField.getText());
       double prix = Double.parseDouble(prixField.getText().replaceAll(",", ""));
       String note = noteField1.getText();
       myControler.ajouterArticle(nom, qty, note, prix);
       this.dispose();
   }//GEN-LAST:event_ajouterButtonActionPerformed

    private void incrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incrButtonActionPerformed
        int currentNum = Integer.parseInt(qtyField.getText());
        currentNum++;
        qtyField.setText(String.valueOf(currentNum));
    }//GEN-LAST:event_incrButtonActionPerformed

    private void decrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrButtonActionPerformed
        int currentNum = Integer.parseInt(qtyField.getText());
        if(currentNum > 0){
            currentNum--;
        }
        qtyField.setText(String.valueOf(currentNum));
    }//GEN-LAST:event_decrButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterButton;
    private javax.swing.JButton decrButton;
    private javax.swing.JButton incrButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JScrollPane noteField;
    private javax.swing.JTextArea noteField1;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JTextField prixField;
    private javax.swing.JLabel prixLabel;
    private javax.swing.JTextField qtyField;
    private javax.swing.JLabel qtyLabel;
    // End of variables declaration//GEN-END:variables
}
