package genieprojet.gui;

import genieprojet.controleurs.CatalogueControleur;
import genieprojet.vente.Article;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.InternationalFormatter;
import javax.swing.text.NumberFormatter;
import genieprojet.util.IObserver;

/**
 *
 * @author Benoit
 */
public final class CatalogueUI extends javax.swing.JFrame implements IObserver {
    private DefaultTableModel myModel;
    private CatalogueControleur myCatalogueControleur;
    private Article selectedArticle;

    /**
     * Creates new form CatalogueUI
     */
    public CatalogueUI() {
        initComponents();
        initTable();
        myCatalogueControleur = new CatalogueControleur();
        myCatalogueControleur.ajouterObserver(this);
        reloadTable();
        addManualListener();
        disableItemFrame();
    }
    
    @Override
    public void update(){
        reloadTable();
    }
    
    public void reloadTable(ArrayList<Article> toFill){
        clearTable();
        fillArticleTable(toFill);
    }
    
    public void reloadTable(){
        clearTable();
        fillArticleTable(myCatalogueControleur.getAllArticles());
    }
    
    private void disableItemFrame(){
        itemFrame.setEnabled(false);
        nameField.setEnabled(false);
        qtyField.setEnabled(false);
        prixField.setEnabled(false);
        noteField.setEnabled(false);
        noteFieldPane.setEnabled(false);
        incrButton.setEnabled(false);
        decrButton.setEnabled(false);
        saveButton.setEnabled(false);
        deleteButton.setEnabled(false);
    }
    
    private void enableItemFrame(){
        itemFrame.setEnabled(true);
        nameField.setEnabled(true);
        qtyField.setEnabled(true);
        prixField.setEnabled(true);
        noteField.setEnabled(true);
        noteFieldPane.setEnabled(true);
        incrButton.setEnabled(true);
        decrButton.setEnabled(true);
        saveButton.setEnabled(true);
        deleteButton.setEnabled(true);
    }

    private void fillArticleTable(ArrayList<Article> toFill) {
        ArrayList<Article> articles = toFill;
        clearTable();
        for (Article a : articles) {
            myModel.addRow(new String[]{
                a.getNom(),
                String.valueOf(a.getQty()),
                String.valueOf(a.getPrix()),
                a.getID()
            });
        }      
    }
    
    private void clearTable(){
        allTable.clearSelection();
        myModel.setRowCount(0);
    }
    
    private void clearSelectedItem(){
        this.selectedArticle = null;
        nameField.setText(null);
        qtyField.setText(null);
        prixField.setText(null);
        codeField.setText(null);
        noteField.setText(null);
        disableItemFrame();
    }
    
    private void initTable(){
        String[] colName = {"Nom", "Quantite", "Prix", "Code"};
        myModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };
        allTable.setModel(myModel);
        myModel.setColumnIdentifiers(colName);
    }

    private void addManualListener() {
        allTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                try{
                    Article selected = myCatalogueControleur.getArticle(
                        allTable.getValueAt(allTable.getSelectedRow(), 3).toString()
                    );
                    setCurrentlySelectedArticle(selected);
                }catch(Exception e){
                    //No row to select
                }
            }
        });
    }

    private void setCurrentlySelectedArticle(Article toSet) {
        this.selectedArticle = toSet;
        nameField.setText(this.selectedArticle.getNom());
        qtyField.setText(String.valueOf(this.selectedArticle.getQty()));
        prixField.setText(String.valueOf(this.selectedArticle.getPrix()));
        codeField.setText(this.selectedArticle.getID());
        noteField.setText(this.selectedArticle.getNote());
        enableItemFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemFrame = new javax.swing.JInternalFrame();
        deleteButton = new javax.swing.JButton();
        nomLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        qtyLabel = new javax.swing.JLabel();
        NumberFormat myFormat = NumberFormat.getIntegerInstance();
        myFormat.setMinimumIntegerDigits(0);
        NumberFormatter numberFormatter = new NumberFormatter(myFormat);
        numberFormatter.setValueClass(Long.class);
        numberFormatter.setAllowsInvalid(false);
        qtyField = new javax.swing.JFormattedTextField(numberFormatter);
        prixLabel = new javax.swing.JLabel();
        NumberFormat format = DecimalFormat.getInstance();
        format.setMinimumFractionDigits(2);
        format.setMaximumFractionDigits(2);
        format.setRoundingMode(RoundingMode.HALF_UP);
        InternationalFormatter formatter = new InternationalFormatter(format);
        formatter.setAllowsInvalid(false);
        prixField = new javax.swing.JFormattedTextField(formatter);
        codeLabel = new javax.swing.JLabel();
        codeField = new javax.swing.JTextField();
        noteLabel = new javax.swing.JLabel();
        noteFieldPane = new javax.swing.JScrollPane();
        noteField = new javax.swing.JTextArea();
        incrButton = new javax.swing.JButton();
        decrButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        itemPanel = new javax.swing.JTabbedPane();
        allPanel = new javax.swing.JScrollPane();
        allTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Outil de gestion du catalogue");
        setName("Outil de gestion du catalogue"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                CatalogueUI.this.windowClosing(evt);
            }
        });

        itemFrame.setTitle("Article");
        itemFrame.setVisible(true);

        deleteButton.setText("Supprimer");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        nomLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomLabel.setText("Nom:");

        qtyLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qtyLabel.setText("Quantité:");

        prixLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prixLabel.setText("Prix:");

        codeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        codeLabel.setText("Code:");

        codeField.setEditable(false);

        noteLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        noteLabel.setText("Note:");

        noteField.setColumns(20);
        noteField.setRows(5);
        noteFieldPane.setViewportView(noteField);

        incrButton.setText("+");
        incrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incrButtonActionPerformed(evt);
            }
        });

        decrButton.setText("-");
        decrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Sauvegarder");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout itemFrameLayout = new javax.swing.GroupLayout(itemFrame.getContentPane());
        itemFrame.getContentPane().setLayout(itemFrameLayout);
        itemFrameLayout.setHorizontalGroup(
            itemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemFrameLayout.createSequentialGroup()
                        .addComponent(nomLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemFrameLayout.createSequentialGroup()
                        .addComponent(qtyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(qtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(incrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemFrameLayout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemFrameLayout.createSequentialGroup()
                        .addGroup(itemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codeLabel)
                            .addComponent(noteLabel)
                            .addComponent(prixLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(itemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codeField, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(noteFieldPane)
                            .addComponent(prixField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        itemFrameLayout.setVerticalGroup(
            itemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 23, Short.MAX_VALUE)
                .addGroup(itemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyField, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(qtyLabel)
                    .addComponent(incrButton)
                    .addComponent(decrButton))
                .addGap(18, 18, 18)
                .addGroup(itemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prixLabel)
                    .addComponent(prixField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(itemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(codeLabel))
                .addGap(18, 18, 18)
                .addGroup(itemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noteLabel)
                    .addComponent(noteFieldPane, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(itemFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        searchButton.setText("Rechercher");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        addButton.setText("Ajouter");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Fermer");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        itemPanel.setName("All"); // NOI18N

        allTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom", "Quantité", "Prix", "Code"
            }
        ));
        allPanel.setViewportView(allTable);
        if (allTable.getColumnModel().getColumnCount() > 0) {
            allTable.getColumnModel().getColumn(1).setPreferredWidth(30);
            allTable.getColumnModel().getColumn(2).setPreferredWidth(30);
        }
        allTable.getAccessibleContext().setAccessibleName("allTable");

        itemPanel.addTab("Articles", allPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(addButton))
                    .addComponent(itemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(itemFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemFrame)
                    .addComponent(itemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(addButton)
                    .addComponent(closeButton))
                .addContainerGap())
        );

        itemPanel.getAccessibleContext().setAccessibleName("All");
        itemPanel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        ArrayList<Article> myResults = myCatalogueControleur.findArticle(searchField.getText());
        reloadTable(myResults);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.windowClosing(null);
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

   private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
       new AddItemWindow(myCatalogueControleur);
   }//GEN-LAST:event_addButtonActionPerformed

   private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
       myCatalogueControleur.retirerArticle(selectedArticle.getID());
       clearSelectedItem();
       reloadTable();
   }//GEN-LAST:event_deleteButtonActionPerformed

    private void windowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosing
        new PortailUI().setVisible(true);
    }//GEN-LAST:event_windowClosing

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        myCatalogueControleur.saveArticle(
            selectedArticle,
            nameField.getText(),
            Integer.parseInt(qtyField.getText()),
            Double.parseDouble(prixField.getText()),
            noteField.getText()
        );
    }//GEN-LAST:event_saveButtonActionPerformed

    private void incrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incrButtonActionPerformed
        int currentNum = Integer.parseInt(qtyField.getText());
        currentNum++;
        qtyField.setText(String.valueOf(currentNum));
    }//GEN-LAST:event_incrButtonActionPerformed

    private void decrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrButtonActionPerformed
        int currentNum = Integer.parseInt(qtyField.getText());
        if(currentNum > 0){
            currentNum--;
        }
        qtyField.setText(String.valueOf(currentNum));
    }//GEN-LAST:event_decrButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JScrollPane allPanel;
    private javax.swing.JTable allTable;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField codeField;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JButton decrButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton incrButton;
    private javax.swing.JInternalFrame itemFrame;
    private javax.swing.JTabbedPane itemPanel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTextArea noteField;
    private javax.swing.JScrollPane noteFieldPane;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JTextField prixField;
    private javax.swing.JLabel prixLabel;
    private javax.swing.JTextField qtyField;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
