/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package genieprojet.gui;

import genieprojet.annuaire.Adresse;
import genieprojet.controleurs.AnnuaireControleur;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Coq
 */
public class CreateClientUI extends javax.swing.JFrame {

    /**
     * Creates new form CreateClientUI
     */
    AnnuaireControleur controller;

    public CreateClientUI(AnnuaireControleur controller) {
        initComponents();
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientInfoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nom2Label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        codeField = new javax.swing.JTextField();
        nom2Field = new javax.swing.JTextField();
        civicField = new javax.swing.JTextField();
        NumberFormat myFormat = NumberFormat.getIntegerInstance();
        myFormat.setMinimumIntegerDigits(0);
        NumberFormatter numberFormatter = new NumberFormatter(myFormat);
        numberFormatter.setValueClass(Long.class);
        numberFormatter.setAllowsInvalid(false);
        ageField = new javax.swing.JFormattedTextField(numberFormatter);
        telField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rueField = new javax.swing.JTextField();
        villeField = new javax.swing.JTextField();
        provinceField = new javax.swing.JTextField();
        nomField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        deleteButton1 = new javax.swing.JButton();
        typeBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Type de client :");

        jLabel3.setText("Nom :");

        nom2Label.setText("Prénom :");

        jLabel5.setText("Adresse :");

        ageLabel.setText("Âge :");

        jLabel7.setText("Code Postal :");

        jLabel8.setText("Numéro de téléphone :");

        codeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeFieldActionPerformed(evt);
            }
        });

        nom2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom2FieldActionPerformed(evt);
            }
        });

        civicField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                civicFieldActionPerformed(evt);
            }
        });

        ageField.setText("0");

        telField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Rue :");

        jLabel9.setText("No civique :");

        jLabel10.setText("Ville :");

        jLabel11.setText("Province :");

        rueField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rueFieldActionPerformed(evt);
            }
        });

        villeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villeFieldActionPerformed(evt);
            }
        });

        provinceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinceFieldActionPerformed(evt);
            }
        });

        nomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomFieldActionPerformed(evt);
            }
        });

        addButton.setText("Sauvegarder");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton1.setText("Annuler");
        deleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton1ActionPerformed(evt);
            }
        });

        typeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Particulier", "Entreprise" }));
        typeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clientInfoPanelLayout = new javax.swing.GroupLayout(clientInfoPanel);
        clientInfoPanel.setLayout(clientInfoPanelLayout);
        clientInfoPanelLayout.setHorizontalGroup(
            clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientInfoPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(clientInfoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(23, 23, 23)
                                .addComponent(civicField))
                            .addGroup(clientInfoPanelLayout.createSequentialGroup()
                                .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11))
                                .addGap(31, 31, 31)
                                .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(villeField)
                                    .addComponent(rueField)
                                    .addComponent(provinceField)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientInfoPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteButton1)
                        .addGap(18, 18, 18)
                        .addComponent(addButton))
                    .addGroup(clientInfoPanelLayout.createSequentialGroup()
                        .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(clientInfoPanelLayout.createSequentialGroup()
                                        .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(nom2Label))
                                        .addGap(54, 54, 54))
                                    .addGroup(clientInfoPanelLayout.createSequentialGroup()
                                        .addComponent(ageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(51, 51, 51)))
                                .addGroup(clientInfoPanelLayout.createSequentialGroup()
                                    .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)))
                            .addGroup(clientInfoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(64, 64, 64)))
                        .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codeField)
                            .addComponent(telField)
                            .addComponent(ageField)
                            .addComponent(nom2Field)
                            .addComponent(typeBox, 0, 210, Short.MAX_VALUE)
                            .addComponent(nomField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        clientInfoPanelLayout.setVerticalGroup(
            clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(telField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(civicField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(villeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(provinceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(clientInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(deleteButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(clientInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(clientInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeFieldActionPerformed

    private void nom2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom2FieldActionPerformed

    private void civicFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_civicFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_civicFieldActionPerformed

    private void telFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telFieldActionPerformed

    private void rueFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rueFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rueFieldActionPerformed

    private void villeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_villeFieldActionPerformed

    private void provinceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinceFieldActionPerformed

    private void nomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        boolean erreur = false;

        String type = typeBox.getSelectedItem().toString();
        String nom = nomField.getText();
        String nom2 = nom2Field.getText();
        String codePostal = codeField.getText();
        String telNum = telField.getText();
        String age = ageField.getText();

        //Valide l'age
        try {
            int ageInt = Integer.parseInt(age);
        } catch (NumberFormatException e) {
            erreur = true;
            JOptionPane.showMessageDialog(this, "Veuillez entrer un âge valide");
        }
        if (nom.length() < 3) {
            erreur = true;
            JOptionPane.showMessageDialog(this, "Veuillez entrer un nom valide (plus de 3 caractères)");
        }
        if (codePostal.equals("") || telNum.equals("")) {
            erreur = true;
            JOptionPane.showMessageDialog(this, "Les champs code postal et numéro de téléphone sont obligatoires");
        }

        if (erreur) {

        } else {
            Adresse adresse = new Adresse(civicField.getText(), rueField.getText(), villeField.getText(), provinceField.getText());
            controller.ajouterClient(type, nom, nom2, adresse, codePostal, telNum, age);

            this.dispose();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_deleteButton1ActionPerformed

    private void typeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeBoxActionPerformed
        if (typeBox.getSelectedItem().toString().equals("Entreprise")) {
            nom2Label.setText("Nom du responsable");
            ageLabel.disable();
            ageField.disable();
        } else {
            nom2Label.setText("Prénom");
            ageLabel.enable();
            ageField.enable();
        }
    }//GEN-LAST:event_typeBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField civicField;
    private javax.swing.JPanel clientInfoPanel;
    private javax.swing.JTextField codeField;
    private javax.swing.JButton deleteButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nom2Field;
    private javax.swing.JLabel nom2Label;
    private javax.swing.JTextField nomField;
    private javax.swing.JTextField provinceField;
    private javax.swing.JTextField rueField;
    private javax.swing.JTextField telField;
    private javax.swing.JComboBox typeBox;
    private javax.swing.JTextField villeField;
    // End of variables declaration//GEN-END:variables
}
