/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package genieprojet.gui;

import genieprojet.annuaire.Annuaire;
import genieprojet.annuaire.Client;
import genieprojet.controleurs.VenteControleur;
import genieprojet.vente.Article;
import genieprojet.vente.Catalogue;
import genieprojet.vente.LigneArticle;
import genieprojet.vente.Registre;
import genieprojet.vente.Vente;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import genieprojet.util.IObserver;

/**
 *
 * @author Benoit
 */
public class VenteUI extends javax.swing.JFrame implements IObserver {
    private final ChooserUI chooserArticles;
    private final ChooserUI chooserClients;
    private final ChooserUI chooserVentes;
    private VenteControleur controleur;
    private Vente vente;

    /**
     * Creates new form BaseUI
     */
    public VenteUI() {
        initComponents();
        chooserArticles = new ChooserUI<>(this, true, Catalogue.getInstance().getAllArticles());
        chooserClients = new ChooserUI<>(this, true, Annuaire.getInstance().getAllClients());
        chooserVentes = new ChooserUI<>(this, true, Registre.getInstance().getAllVentes());
    }
    
    public boolean demanderConfirmation(String message) {
        return JOptionPane.showConfirmDialog(rootPane, message, message, JOptionPane.YES_NO_OPTION, JOptionPane.YES_NO_OPTION) == 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        btnNouvelle = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnOuvrir = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ctlProvince = new javax.swing.JComboBox();
        btnPaiementDiffere = new javax.swing.JButton();
        btnPaiement = new javax.swing.JButton();
        btnConfirmer = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        factureSPane = new javax.swing.JScrollPane();
        facturePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        valNumFacture = new javax.swing.JLabel();
        valSousTotal = new javax.swing.JLabel();
        valTFed = new javax.swing.JLabel();
        valTPro = new javax.swing.JLabel();
        valTotal = new javax.swing.JLabel();
        valPaiements = new javax.swing.JLabel();
        valSolde = new javax.swing.JLabel();
        editorPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVenteArticles = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ctlNoArticle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ctlQteArticle = new javax.swing.JTextField();
        btnAjouterArticle = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ctlNoClient = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                VenteUI.this.windowClosing(evt);
            }
        });

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnNouvelle.setText("Nouvelle");
        btnNouvelle.setFocusable(false);
        btnNouvelle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNouvelle.setMargin(new java.awt.Insets(5, 14, 5, 14));
        btnNouvelle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNouvelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouvelleActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNouvelle);
        jToolBar1.add(jSeparator1);

        btnOuvrir.setText("Ouvrir");
        btnOuvrir.setFocusable(false);
        btnOuvrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOuvrir.setMargin(new java.awt.Insets(5, 14, 5, 14));
        btnOuvrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOuvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOuvrirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOuvrir);
        jToolBar1.add(jSeparator2);

        jLabel11.setText("Province (Taxes) :");

        ctlProvince.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "QUEBEC", "ONTARIO", "SASKATCHEWAN" }));
        ctlProvince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctlProvinceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(334, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(ctlProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ctlProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel3);

        btnPaiementDiffere.setText("Paiement différé");
        btnPaiementDiffere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaiementDiffereActionPerformed(evt);
            }
        });

        btnPaiement.setText("Paiement");
        btnPaiement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaiementActionPerformed(evt);
            }
        });

        btnConfirmer.setText("Enregistrer");
        btnConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmerActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        facturePanel.setBackground(new java.awt.Color(255, 255, 255));
        facturePanel.setPreferredSize(new java.awt.Dimension(180, 120));

        jLabel4.setText("Facture : ");

        jLabel5.setText("Sous-total :");

        jLabel6.setText("Taxes fédérales :");

        jLabel7.setText("Taxes provinciales :");

        jLabel8.setText("Total :");

        jLabel9.setText("Paiements : ");

        jLabel10.setText("Solde :");

        valNumFacture.setText("<num_facture>");

        valSousTotal.setText("<stotal>");

        valTFed.setText("<tax_fed>");

        valTPro.setText("<tax_pro>");

        valTotal.setText("<total>");

        valPaiements.setText("<paiement>");

        valSolde.setText("<solde>");

        javax.swing.GroupLayout facturePanelLayout = new javax.swing.GroupLayout(facturePanel);
        facturePanel.setLayout(facturePanelLayout);
        facturePanelLayout.setHorizontalGroup(
            facturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(facturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(facturePanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valNumFacture))
                    .addGroup(facturePanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valSolde))
                    .addGroup(facturePanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valSousTotal))
                    .addGroup(facturePanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valTFed))
                    .addGroup(facturePanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(valTPro))
                    .addGroup(facturePanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valTotal))
                    .addGroup(facturePanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valPaiements)))
                .addContainerGap())
        );
        facturePanelLayout.setVerticalGroup(
            facturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facturePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(facturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(valNumFacture))
                .addGap(18, 18, 18)
                .addGroup(facturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(valSousTotal))
                .addGap(18, 18, 18)
                .addGroup(facturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(valTFed))
                .addGap(18, 18, 18)
                .addGroup(facturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(valTPro))
                .addGap(18, 18, 18)
                .addGroup(facturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(valTotal))
                .addGap(18, 18, 18)
                .addGroup(facturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(valPaiements))
                .addGap(18, 18, 18)
                .addGroup(facturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(valSolde))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        factureSPane.setViewportView(facturePanel);

        editorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tableVenteArticles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Article", "Qte", "Prix"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVenteArticles.setEnabled(false);
        tableVenteArticles.setGridColor(new java.awt.Color(229, 229, 229));
        tableVenteArticles.setRowHeight(20);
        tableVenteArticles.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tableVenteArticles);
        if (tableVenteArticles.getColumnModel().getColumnCount() > 0) {
            tableVenteArticles.getColumnModel().getColumn(1).setResizable(false);
            tableVenteArticles.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        jLabel1.setText("Article :");

        jLabel2.setText("Qte :");

        ctlQteArticle.setText("1");
        ctlQteArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctlQteArticleActionPerformed(evt);
            }
        });

        btnAjouterArticle.setText("Ajouter");
        btnAjouterArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterArticleActionPerformed(evt);
            }
        });

        jButton5.setText("Parcourir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ctlNoArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ctlQteArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAjouterArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(ctlNoArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(ctlQteArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAjouterArticle)
                .addComponent(jButton5))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(54, 36));

        jLabel3.setText("Client");

        jButton4.setText("Parcourir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(ctlNoClient, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ctlNoClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout editorPanelLayout = new javax.swing.GroupLayout(editorPanel);
        editorPanel.setLayout(editorPanelLayout);
        editorPanelLayout.setHorizontalGroup(
            editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );
        editorPanelLayout.setVerticalGroup(
            editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editorPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(factureSPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPaiement, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPaiementDiffere, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConfirmer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addComponent(editorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(factureSPane, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPaiementDiffere)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnnuler)
                    .addComponent(btnConfirmer)
                    .addComponent(btnPaiement))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOuvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOuvrirActionPerformed
        chooserVentes.setLocationRelativeTo(this);
        chooserVentes.update();
        chooserVentes.setVisible(true);
        Vente vente = (Vente)chooserVentes.getValue();
        if (vente != null) {
            controleur.ouvrirVente(vente);
        }
    }//GEN-LAST:event_btnOuvrirActionPerformed

    private void btnNouvelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouvelleActionPerformed
        controleur.nouvelleVente();
    }//GEN-LAST:event_btnNouvelleActionPerformed

    private void btnConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmerActionPerformed
        controleur.confirmerVente(ctlNoClient.getText());
    }//GEN-LAST:event_btnConfirmerActionPerformed

    private void btnAjouterArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterArticleActionPerformed
        try {
            controleur.ajouterArticle(ctlNoArticle.getText(), Integer.parseInt(ctlQteArticle.getText()));
        } catch (NumberFormatException e) {
            showMessage("Quantite invalide");
        }
    }//GEN-LAST:event_btnAjouterArticleActionPerformed

    private void ctlQteArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctlQteArticleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctlQteArticleActionPerformed

    public void showMessage(String message) {
        JOptionPane.showMessageDialog(rootPane, message);
    }

    @Override
    public void update() {
        render();
    }

    private void windowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosing
        new PortailUI().setVisible(true);
    }//GEN-LAST:event_windowClosing

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        chooserClients.setLocationRelativeTo(this);
        chooserClients.update();
        chooserClients.setVisible(true);
        Client client = (Client)chooserClients.getValue();
        if (client != null) {
            ctlNoClient.setText(client.getID());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        chooserArticles.setLocationRelativeTo(this);
        chooserArticles.update();
        chooserArticles.setVisible(true);
        Article article = (Article)chooserArticles.getValue();
        if (article != null) {
            ctlNoArticle.setText(article.getID());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        windowClosing(null);
        dispose();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnPaiementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaiementActionPerformed
        String paiement = JOptionPane.showInputDialog("Entrer le paiement : ");
        try {
            if (paiement != null) {
                controleur.ajouterPaiement(Double.valueOf(paiement));
            }
        } catch (NumberFormatException e) {
            showErreur("Paiement invalide");
        }
    }//GEN-LAST:event_btnPaiementActionPerformed

    private void btnPaiementDiffereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaiementDiffereActionPerformed
        controleur.confirmerVente(ctlNoClient.getText());
    }//GEN-LAST:event_btnPaiementDiffereActionPerformed

    private void ctlProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctlProvinceActionPerformed
        controleur.setProvince((String)ctlProvince.getModel().getSelectedItem());
    }//GEN-LAST:event_ctlProvinceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterArticle;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnConfirmer;
    private javax.swing.JButton btnNouvelle;
    private javax.swing.JButton btnOuvrir;
    private javax.swing.JButton btnPaiement;
    private javax.swing.JButton btnPaiementDiffere;
    private javax.swing.JTextField ctlNoArticle;
    private javax.swing.JTextField ctlNoClient;
    private javax.swing.JComboBox ctlProvince;
    private javax.swing.JTextField ctlQteArticle;
    private javax.swing.JPanel editorPanel;
    private javax.swing.JPanel facturePanel;
    private javax.swing.JScrollPane factureSPane;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tableVenteArticles;
    private javax.swing.JLabel valNumFacture;
    private javax.swing.JLabel valPaiements;
    private javax.swing.JLabel valSolde;
    private javax.swing.JLabel valSousTotal;
    private javax.swing.JLabel valTFed;
    private javax.swing.JLabel valTPro;
    private javax.swing.JLabel valTotal;
    // End of variables declaration//GEN-END:variables

    public void render() {
        renderFacture();
        renderEditor();
    }

    private void renderEditor() {
        // render table values
        DefaultTableModel model = (DefaultTableModel) tableVenteArticles.getModel();

        // reset
        model.setRowCount(0);

        // repopulate
        for (LigneArticle la : vente.getLignes()) {
            Article article = la.getArticle();
            Object[] row = {article.getID(), article.getNom(), la.getQte(), article.getPrix()};
            model.addRow(row);
        }
        model.fireTableDataChanged();
        
        // le client
        String id = vente.getClient() != null ? vente.getClient().getID() : ctlNoClient.getText();
        ctlNoClient.setText(id);
    }
    
    public void clearFields() {
        ctlNoClient.setText("");
        ctlNoArticle.setText("");
        ctlQteArticle.setText("1");
    }

    private void renderFacture() {
        NumberFormat f = NumberFormat.getCurrencyInstance();
        valNumFacture.setText(String.valueOf(vente.getNumero()));
        valSousTotal.setText(f.format(vente.getSousTotal()));
        valTFed.setText(f.format(vente.getTaxesFederales()));
        valTPro.setText(f.format(vente.getTaxesProvinciales()));
        valTotal.setText(f.format(vente.getTotal()));
        valPaiements.setText(f.format(vente.getPaiementsTotal()));
        valSolde.setText(f.format(vente.getSolde()));
    }

    public void setVente(Vente vente) {
        // ne plus observer l'ancienne vente
        if (this.vente != null) {
            this.vente.retirerObserver(this);
        }
        
        // observer la nouvelle vente
        this.vente = vente;
        this.vente.ajouterObserver(this);
        this.render();
    }

    public void setControleur(VenteControleur controleur) {
        this.controleur = controleur;
    }

    public void showErreur(String message) {
        JOptionPane.showMessageDialog(rootPane, message);
    }
}
